twig:
    default_path: '%kernel.project_dir%/templates'

    # personnalisation de notre form (le theme utilisé sera ce template bootstrap là)
    form_themes: ['bootstrap_4_layout.html.twig']
when@test:
    twig:
        strict_variables: true
